version: 0.2

env:
  parameter-store:
    AWS_REGION: "/buet/hackathon/aws-region"
    ECR_REPOSITORY_URL: "/buet/hackathon/ecr-repo-url"
    VERSION: "/buet/hackathon/version"
    K8S_CLUSTER_NAME: "/buet/hackathon/k8s-cluster-name"
    K8S_NAMESPACE: "/buet/hackathon/k8s-namespace"
    STUDENT_SERVICE_APPLICATION_SETTINGS: "/buet/hackathon/student-service-application-settings"
    STUDENT_SERVICE_DB_SETTINGS: "/buet/hackathon/student-service-db-settings"
    COURSE_SERVICE_APPLICATION_SETTINGS: "/buet/hackathon/course-service-application-settings"
    COURSE_SERVICE_DB_SETTINGS: "/buet/hackathon/course-service-db-settings"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Starting build phases...

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $AWS_REGION $ECR_REPOSITORY_URL
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URL

  build:
    commands:
      - echo Building Docker image for Course Service...
      - docker build -t $ECR_REPOSITORY_URL/student:$VERSION -f student/Dockerfile student
      - docker push $ECR_REPOSITORY_URL/student:$VERSION
      
      - echo Building Docker image for Student Service...
      - docker build -t $ECR_REPOSITORY_URL/course:$VERSION -f course/Dockerfile course
      - docker push $ECR_REPOSITORY_URL/course:$VERSION

  post_build:
    commands:
      - echo All services have been built and pushed to ECR.
      - mkdir tmp
      
      - echo Getting application settings in tmp directory...
      - echo $COURSE_SERVICE_APPLICATION_SETTINGS > ./tmp/course.env
      - echo $STUDENT_SERVICE_APPLICATION_SETTINGS > ./tmp/student.env

      - echo Getting database settings in tmp directory...
      - echo $COURSE_SERVICE_DB_SETTINGS > ./tmp/course.json
      - echo $STUDENT_SERVICE_DB_SETTINGS > ./tmp/student.json

      - echo Creating K8s Namespace...
      - kubectl create namespace $K8S_CLUSTER_NAME
      
      - echo Creating EKS credential...
      - aws eks --region $AWS_REGION update-kubeconfig --name $K8S_CLUSTER_NAME

      - echo Removing old secrets...
      - kubectl -n $K8S_NAMESPACE delete secret course-db-settings course-app-settings --ignore-not-found
      - kubectl -n $K8S_NAMESPACE delete secret student-db-settings student-app-settings --ignore-not-found

      - echo Creating application secret in Kubernetes...
      - kubectl -n $K8S_NAMESPACE create secret generic course-app-settings --from-env-file=./tmp/course.env
      - kubectl -n $K8S_NAMESPACE create secret generic student-app-settings --from-env-file=./tmp/student.env

      - echo Creating DB secret in Kubernetes...
      - kubectl -n $K8S_NAMESPACE create secret generic course-db-settings --from-file=./tmp/course.json
      - kubectl -n $K8S_NAMESPACE create secret generic student-db-settings --from-file=./tmp/student.json
