version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    image: frontend
    ports:
      - '4200:80'
    stdin_open: true
    tty: true

  registration:
    build: 
      context: ./registration
    container_name: registration
    image: registration
    ports:
      - '8000:8000'

  course:
    build: 
      context: ./course
    container_name: course
    image: course
    ports:
      - '8080:8080'

volumes:
  student_data:
  course_data:
