apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hackathon-ingress
  namespace: buet-hackathon-namespace
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:863518452741:certificate/6c378461-1ff8-4702-82db-a1a12b0a9524
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  rules:
    - host: api.course.projectsbd.me
      http:
        paths:
          - path: /v1/course
            pathType: Prefix
            backend:
              service:
                name: course-service
                port:
                  number: 80
    - host: api.registration.projectsbd.me
      http:
        paths:
          - path: /v1/registration
            pathType: Prefix
            backend:
              service:
                name: registration-service
                port:
                  number: 80
