---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: buet-hackathon-namespace
  name: registration-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration
  template:
    metadata:
      labels:
        app: registration
    spec:
      containers:
        - name: registration
          image: 863518452741.dkr.ecr.ap-south-1.amazonaws.com/student:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: registration-app-settings
          env:
            - name: DATABASES
              valueFrom:
                secretKeyRef:
                  name: registration-db-settings
                  key: student.json
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: buet-hackathon-namespace
  name: registration-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: registration
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: registration-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: registration-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50